version: "3.8"
services:
  # Database
  database_mysql_dev:
    container_name: database_mysql_dev
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
    restart: always
    networks:
      - backend_dev
    volumes:
      - data-volume_dev:/var/lib/mysql

  # Backend
  backend_node_dev:
    build: ./backend
    restart: always
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    environment: 
      - NODE_DATABASE_HOST=database_mysql_dev
    restart: always
    ports:
      - "4008:4008"
    networks:
      - backend_dev
      - frontend_dev
    depends_on:
      - database_mysql_dev

  # Frontend
  frontend_react_dev:
    build: 
      context: ./frontend
      args:
      - REACT_APP_API_URL= ${API_URL_DEV}
      - REACT_APP_FRONTEND_URL= ${FRONTEND_URL_DEV}
    env_file: .env
    ports:
      - "80:80"
      - "4012:9090"
    networks:
      - frontend_dev
    depends_on:
      - backend_node_dev

  # Pagecache
  pagecache_dev:
    image: memcached
    ports:
      - "11211:11211"
    command: -m 64
    networks:
      - frontend_dev

# Names for networks
networks:
  backend_dev:
    driver: bridge
  frontend_dev:
    driver: bridge

# Names for volumes
volumes:
  data-volume_dev:
