version: "3.8"
services:
  # Database
  database_mysql_prod:
    container_name: database_mysql_prod
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend_prod
    volumes:
      - data-volume_prod:/var/lib/mysql

  # Backend
  backend_node_prod:
    build:
      context: ./backend
      dockerfile: ./docker/prod.Dockerfile
    restart: always
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    environment: 
      - NODE_DATABASE_HOST=database_mysql_prod
      - NODE_DATABASE_PORT=3306
      - NODE_DATABASE_USER=${MYSQL_USER}
      - NODE_DATABASE_PASS=${MYSQL_USER_PASSWORD}
      - NODE_DATABASE_DBNAME=${MYSQL_DATABASE_NAME}
    restart: always
    ports:
      - "4008:4008"
    networks:
      - backend_prod
      - frontend_prod
    depends_on:
      - database_mysql_prod

  # Frontend
  frontend_react_prod:
    build: 
      context: ./frontend
      dockerfile: ./docker/prod.Dockerfile
      args:
      - REACT_APP_API_URL= ${API_URL_PROD}
      - REACT_APP_FRONTEND_URL= ${FRONTEND_URL_PROD}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_prod
    depends_on:
      - backend_node_prod

# Names for networks
networks:
  backend_prod:
    driver: bridge
  frontend_prod:
    driver: bridge

# Names for volumes
volumes:
  data-volume_prod:
