version: "3.4"
services:
  # Database
  database_mysql:
    container_name: database_mysql
    build: ./database
    restart: always
    networks:
      - backend
    ports:
      - "3306"
    volumes:
      - data-volume:/var/lib/mysql
  # Backend
  backend_node:
    build: ./backend
    ports:
      - "4008:4008"
    networks:
      - backend
      - frontend
    depends_on:
      - database_mysql
  # Frontend
  frontend_react:
    build: ./frontend
    ports:
      - "80:80"
      - "4012:9090"
    networks:
      - frontend
    depends_on:
      - backend_node
  pagecache:
    image: memcached
    ports:
      - "11211:11211"
    command: -m 64
    networks:
      - frontend
# Names for network
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
# Names our volume
volumes:
  data-volume:
