name: Deploy test

on:
  push:
    branches: [ master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    name: Test & Build Artifacts
    steps:
      - uses: actions/checkout@v2
   
  deploy:
    name: Push artifacts to EC2 instance
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: frontend

      # Copy build folder content to EC2
      - name: Copy public files to remote EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          rm: true
          source: "frontend"
          target: "${{ secrets.REMOTE_DIR }}"
