name: Deploy dev and run E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
# deploy whole folder on server   
  deploy:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        rm: true
        source: "*"
        target: "${{ secrets.REMOTE_DIR }}"

# force build docker, run install dependencies and run E2E tests
    - name: Rebuild docker and run E2E tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cp /home/ubuntu/file_test_script.txt /home/ubuntu/test/
          cd /home/ubuntu/test/ && docker-compose -f docker-compose.dev.yml up -d --build --force-recreate
          yarn --cwd /home/ubuntu/test/frontend/ install
          yarn --cwd /home/ubuntu/test/frontend/ run test_tests
