name: Deploy test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        rm: true
        source: "*"
        target: "${{ secrets.REMOTE_DIR }}"

    - name: script test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cp /home/ubuntu/file_test_script.txt /home/ubuntu/test/
          docker-compose -f /home/ubuntu/test/docker-compose.test.yml up -d --build --force-recreate
          yarn --cwd /home/ubuntu/test/frontend/ install
          yarn --cwd /home/ubuntu/test/frontend/ run test_tests
